### DISCUSSION TITLE
Allow template placement within subdirectories

### DISCUSSION THREAD

**Discussion by rdzotz** [microsoft/dstoolkit-mlops-base#35] [Ideas]
I believe it might make sense to include a DIR variable within the configuration-aml.variables.yml which allows the template to be placed within any subdirectory. This environment variables should then be input into all the template .yml files for example:

```
- job: aml_compute_training
  displayName: 'Deploy AML Training Compute'
  steps:
  - template: utils/run-aml-python-code.template.yml
    parameters:
      serviceConnection: ${{parameters.serviceConnection}}
      resourceGroup: ${{parameters.resourceGroup}}
      amlWorkspace: ${{parameters.amlWorkspace}}
      scriptPath: ${{variable.dir}}/operation/execution/create_compute.py
      scriptArguments: |
        --name $(AML_TRAINING_COMPUTE) \
        --config-path ${{variables.dir}}/configuration/compute/${{parameters.environment}}-training-compute.yml
      scriptExtraDependencies: pyyaml
```
